from __future__ import annotations

import json
import math
import os
from functools import lru_cache
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any
from dotenv import load_dotenv
from gemini_client import generate_text

try:
    PROJECT_ROOT = Path(__file__).resolve().parents[2]
except IndexError:
    PROJECT_ROOT = Path(__file__).resolve().parent

DATA_DIR             = PROJECT_ROOT / "data" / "processed"
SUMMARY_PATH         = DATA_DIR / "hies_state_summary.json"
EXPENDITURE_AGE_PATH = DATA_DIR / "expenditure_by_age.json"

STATE_ALIASES = {
    "penang":           "Pulau Pinang",
    "pulau pinang":     "Pulau Pinang",
    "kuala lumpur":     "W.P. Kuala Lumpur",
    "wp kuala lumpur":  "W.P. Kuala Lumpur",
    "w.p. kuala lumpur":"W.P. Kuala Lumpur",
    "labuan":           "W.P. Labuan",
    "w.p. labuan":      "W.P. Labuan",
    "putrajaya":        "W.P. Putrajaya",
    "w.p. putrajaya":   "W.P. Putrajaya",
}

# Maps frontend spending/commitment label (lowercase) to expenditure_by_age.json key.
# Used for anomaly detection against DOSM 25-34 benchmarks loaded via ETL.
CATEGORY_TO_BENCHMARK = {
    # Variable spending (Section C)
    "food & drinks":                     "food_beverages",
    "groceries":                         "food_beverages",
    "transport / petrol":                "transport",
    "grab / taxi":                       "transport",
    "entertainment":                     "recreation_culture",
    "shopping / clothing":               "clothing_footwear",
    "gym / sports":                      "recreation_culture",
    "medical / pharmacy":                "health",
    "subscriptions (netflix etc.)":      "communication",
    # Fixed commitments (Section B) — utilities now benchmarked
    "utilities (water/electricity/gas)": "housing_utilities",
    "wifi bill":                         "communication",
    "internet bill":                     "communication",
    "insurance":                         "insurance_finance",
}

DEFAULT_PORT = int(os.environ.get("BACKEND_PORT", "8000"))


@lru_cache(maxsize=1)
def load_summary() -> dict[str, Any]:
    if not SUMMARY_PATH.exists():
        raise FileNotFoundError(
            f"Missing processed dataset: {SUMMARY_PATH}. "
            "Run scripts/etl_pipeline.py first."
        )
    with SUMMARY_PATH.open(encoding="utf-8") as handle:
        return json.load(handle)


@lru_cache(maxsize=1)
def load_expenditure_benchmarks() -> dict[str, Any]:
    """Load DOSM Table 1.8 benchmarks generated by scripts/etl_expenditure.py.

    Falls back to empty dict so the pipeline degrades gracefully if the
    ETL has not been run yet.
    """
    if not EXPENDITURE_AGE_PATH.exists():
        return {}
    with EXPENDITURE_AGE_PATH.open(encoding="utf-8") as handle:
        return json.load(handle)


def get_age_benchmark(age_group: str = "25_34") -> dict[str, float]:
    """Return RM benchmarks for a given age group from the ETL output."""
    return load_expenditure_benchmarks().get("benchmarks", {}).get(age_group, {})


def normalize_state_name(value: str | None) -> str:
    if not value:
        return "Selangor"
    cleaned = " ".join(value.strip().split())
    return STATE_ALIASES.get(cleaned.lower(), cleaned)


def safe_float(value: Any, default: float = 0.0) -> float:
    try:
        if value in (None, ""):
            return default
        return float(value)
    except (TypeError, ValueError):
        return default


def clamp(value: float, minimum: float = 0.0, maximum: float = 100.0) -> float:
    return max(minimum, min(maximum, value))


def round_currency(value: float) -> float:
    return round(max(value, 0.0), 2)


def get_state_benchmark(state: str) -> dict[str, Any]:
    summary = load_summary()
    normalized_state = normalize_state_name(state)
    for row in summary.get("state_summary", []):
        if normalize_state_name(row.get("state")) == normalized_state:
            return row
    first_date = summary.get("date_summary", [{}])
    fallback_row = first_date[0] if first_date else {}
    return {
        "state": normalized_state,
        "avg_income_mean":       fallback_row.get("avg_income_mean", 0),
        "avg_income_median":     fallback_row.get("avg_income_mean", 0),
        "avg_expenditure_mean":  fallback_row.get("avg_expenditure_mean", 0),
        "avg_poverty":           fallback_row.get("avg_poverty", 0),
    }


def sum_dynamic_list(items: list) -> float:
    """Sum amount fields from the new dynamic commitment/spending arrays."""
    return round_currency(sum(safe_float(item.get("amount")) for item in items))


def estimate_deductions(gross_salary: float) -> dict[str, float]:
    epf   = round_currency(gross_salary * 0.11)
    socso = round_currency(min(gross_salary * 0.0035, 19.75))
    eis   = round_currency(gross_salary * 0.002)
    pcb   = round_currency(max((gross_salary - 5000) * 0.03, 0.0))
    total = round_currency(epf + socso + eis + pcb)
    return {
        "epf": epf, "socso": socso, "eis": eis, "pcb": pcb,
        "total": total,
        "take_home": round_currency(gross_salary - total),
    }


def build_risk_flags(take_home: float, commitments: float, spending: float, remaining: float) -> list[str]:
    if take_home <= 0:
        return ["No take-home pay detected"]
    flags: list[str] = []
    if commitments / take_home > 0.5:
        flags.append("Fixed commitments exceed 50% of take-home pay")
    if spending / take_home > 0.35:
        flags.append("Variable spending is above a comfortable range")
    if remaining / take_home < 0.15:
        flags.append("Savings buffer is below the 15% target")
    return flags


def severity_from_ratio(ratio: float) -> str:
    if ratio >= 0.35: return "high"
    if ratio >= 0.2:  return "medium"
    return "low"


def detect_anomalies(all_items: list[dict]) -> list[dict]:
    """Compare each spending/commitment item against DOSM 25-34 age group benchmark.

    Works across both fixed commitments (Section B) and variable spending (Section C)
    so utilities, insurance etc. are benchmarked alongside food and transport.
    Benchmarks are loaded from data/processed/expenditure_by_age.json (ETL output).
    """
    benchmark_25_34 = get_age_benchmark("25_34")
    if not benchmark_25_34:
        return []   # ETL not run yet — degrade gracefully

    anomalies = []
    for item in all_items:
        label     = (item.get("label") or "").lower().strip()
        amount    = safe_float(item.get("amount"))
        bench_key = CATEGORY_TO_BENCHMARK.get(label)
        if not bench_key:
            continue
        benchmark_val = benchmark_25_34.get(bench_key, 0)
        if benchmark_val <= 0:
            continue
        ratio = amount / benchmark_val
        if ratio >= 1.20:   # flag if 20%+ above benchmark
            pct_over = round((ratio - 1) * 100)
            anomalies.append({
                "category":    item.get("label"),
                "your_amount": amount,
                "benchmark":   benchmark_val,
                "pct_over":    pct_over,
                "flag":        f"{pct_over}% above 25-34 avg",
                "severity":    "high" if ratio >= 1.5 else "medium",
            })
    return anomalies


def build_finance_gaps(snapshot: dict[str, Any], benchmark: dict[str, Any], plan: dict[str, Any]) -> list[dict[str, Any]]:
    take_home        = snapshot["take_home"]
    median_income    = safe_float(benchmark.get("avg_income_median"), 0.0)
    benchmark_spending = safe_float(benchmark.get("avg_expenditure_mean"), 0.0)
    savings_goal     = safe_float(snapshot.get("savings_goal"), 0.0)
    target_months    = int(safe_float(snapshot.get("goal_months"), 12)) or 12

    gaps: list[dict[str, Any]] = []

    income_gap_amount = max(median_income - snapshot["gross_salary"], 0.0)
    if income_gap_amount > 0:
        income_gap_ratio = income_gap_amount / median_income if median_income else 0.0
        gaps.append({
            "type": "income_gap", "severity": severity_from_ratio(income_gap_ratio),
            "amount": round_currency(income_gap_amount),
            "message": f"Income is RM {income_gap_amount:,.2f} below the {snapshot['state']} median.",
            "driver": "gross_salary",
        })

    commitment_ratio = snapshot["total_commitments"] / take_home if take_home else 0.0
    if take_home > 0 and commitment_ratio > 0.5:
        gaps.append({
            "type": "cashflow_gap", "severity": severity_from_ratio(commitment_ratio - 0.5),
            "amount": round_currency(snapshot["total_commitments"] - take_home * 0.5),
            "message": "Fixed commitments are consuming too much of take-home pay.",
            "driver": "total_commitments",
        })

    spending_gap_amount = max(snapshot["total_spending"] - benchmark_spending, 0.0)
    if spending_gap_amount > 0:
        spending_gap_ratio = spending_gap_amount / benchmark_spending if benchmark_spending else 0.0
        gaps.append({
            "type": "spending_gap", "severity": severity_from_ratio(spending_gap_ratio),
            "amount": round_currency(spending_gap_amount),
            "message": f"Variable spending is RM {spending_gap_amount:,.2f} above the benchmark average.",
            "driver": "total_spending",
        })

    if savings_goal:
        savings_gap_amount = max((savings_goal / target_months) - snapshot["remaining"], 0.0)
        if savings_gap_amount > 0:
            target_monthly    = savings_goal / target_months if target_months else 0.0
            savings_gap_ratio = savings_gap_amount / target_monthly if target_monthly else 0.0
            gaps.append({
                "type": "savings_gap", "severity": severity_from_ratio(savings_gap_ratio),
                "amount": round_currency(savings_gap_amount),
                "message": "Current leftover cash is not enough to hit the savings goal on time.",
                "driver": "remaining_cash",
            })

    if snapshot["remaining"] <= 0:
        gaps.append({
            "type": "negative_cashflow_gap", "severity": "high",
            "amount": round_currency(abs(snapshot["remaining"])),
            "message": "Monthly cash flow is negative after commitments and spending.",
            "driver": "remaining",
        })

    if not gaps:
        gaps.append({
            "type": "stable_profile", "severity": "low", "amount": 0.0,
            "message": "No critical finance gap detected against the selected benchmark.",
            "driver": "overall_profile",
        })

    return gaps


def build_snapshot(payload: dict[str, Any]) -> tuple[dict[str, Any], dict[str, Any]]:
    state     = normalize_state_name(payload.get("state"))
    benchmark = get_state_benchmark(state)

    gross_salary = round_currency(safe_float(payload.get("gross_salary")))
    deductions   = estimate_deductions(gross_salary)

    # ── FIX: respect dynamic lists, fall back to flat fields ──────────────────
    fixed_list    = payload.get("fixed_commitments", [])
    variable_list = payload.get("variable_spendings", [])

    commitments = (
        sum_dynamic_list(fixed_list) if fixed_list
        else round_currency(
            safe_float(payload.get("rent")) + safe_float(payload.get("study_loan")) +
            safe_float(payload.get("car_loan")) + safe_float(payload.get("phone_bill"))
        )
    )
    spending = (
        sum_dynamic_list(variable_list) if variable_list
        else round_currency(
            safe_float(payload.get("food_spending")) + safe_float(payload.get("transport_spending")) +
            safe_float(payload.get("entertainment"))
        )
    )

    remaining    = round_currency(deductions["take_home"] - commitments - spending)
    median_income = safe_float(benchmark.get("avg_income_median"), 0.0)
    diff_from_median = gross_salary - median_income
    diff_percent = round(abs(diff_from_median / median_income) * 100) if median_income else 0

    # ── Pre-compute anomalies (Python-driven, uses DOSM data) ────────────────
    anomalies = detect_anomalies(fixed_list + variable_list)

    # ── Build bill context lines for Gemini (AI will do the audit reasoning) ─
    phone_provider = (payload.get("phone_provider") or "").strip()
    bill_items = [
        i for i in fixed_list
        if any(k in (i.get("label") or "").lower() for k in ("phone", "wifi", "internet", "broadband", "insurance", "subscription"))
    ]
    if bill_items:
        bill_context_lines = "\n".join(
            f"  - {i.get('label')}: RM {i.get('amount')}/month"
            + (f", provider: {phone_provider}" if phone_provider else " (provider not specified)")
            for i in bill_items
        )
    else:
        bill_context_lines = "  - none declared"

    snapshot = {
        "name":              payload.get("name", "there"),
        "state":             state,
        "gross_salary":      gross_salary,
        "take_home":         deductions["take_home"],
        "epf":               deductions["epf"],
        "socso":             deductions["socso"],
        "eis":               deductions["eis"],
        "pcb":               deductions["pcb"],
        "total_commitments": commitments,
        "total_spending":    spending,
        "remaining":         remaining,
        # ── FIX: store breakdowns so build_recommendations can use them ───────
        "food_spending":     sum(safe_float(i.get("amount")) for i in variable_list if "food" in i.get("label","").lower() or "grocer" in i.get("label","").lower()) or safe_float(payload.get("food_spending")),
        "transport_spending":sum(safe_float(i.get("amount")) for i in variable_list if "transport" in i.get("label","").lower() or "grab" in i.get("label","").lower()) or safe_float(payload.get("transport_spending")),
        "entertainment":     sum(safe_float(i.get("amount")) for i in variable_list if "entertain" in i.get("label","").lower() or "shopping" in i.get("label","").lower()) or safe_float(payload.get("entertainment")),
        "fixed_commitments": fixed_list,
        "variable_spendings":variable_list,
        "anomalies":         anomalies,
        "bill_context_lines":bill_context_lines,
        "benchmark": {
            "median_income":    median_income,
            "mean_expenditure": safe_float(benchmark.get("avg_expenditure_mean"), 0.0),
            "poverty_rate":     safe_float(benchmark.get("avg_poverty"), 0.0),
        },
        "benchmark_comparison": (
            f"Your salary is {diff_percent}% above the {state} median income."
            if diff_from_median >= 0
            else f"Your salary is {diff_percent}% below the {state} median income."
        ),
        "risk_flags": build_risk_flags(deductions["take_home"], commitments, spending, remaining),
    }

    return snapshot, benchmark


def health_score_python(snapshot: dict[str, Any], benchmark: dict[str, Any]) -> tuple[int, str]:
    """Python-calculated fallback score — used only when Gemini fails."""
    take_home = snapshot["take_home"]
    if take_home <= 0:
        return 0, "Critical"

    remaining_ratio  = snapshot["remaining"] / take_home
    commitment_ratio = snapshot["total_commitments"] / take_home
    spending_ratio   = snapshot["total_spending"] / take_home
    benchmark_gap    = snapshot["gross_salary"] - safe_float(benchmark.get("avg_income_median"), 0.0)

    score = 55
    score += remaining_ratio * 45
    score -= max(commitment_ratio - 0.35, 0) * 70
    score -= max(spending_ratio  - 0.25, 0) * 35
    if benchmark_gap > 0:
        score += 5

    score = int(clamp(score))
    label = "Strong" if score >= 75 else ("Needs Attention" if score >= 55 else "At Risk")
    return score, label


def build_plan(snapshot: dict[str, Any], benchmark: dict[str, Any], payload: dict[str, Any]) -> dict[str, Any]:
    """Generates a financial plan — single Gemini call returning all 6 AI features as structured JSON."""

    # ── STEP 1: Base values ────────────────────────────────────────────────────
    take_home         = snapshot.get("take_home", 0)
    total_commitments = snapshot.get("total_commitments", 0)
    total_spending    = snapshot.get("total_spending", 0)
    remaining         = max(snapshot.get("remaining", 0), 0)
    goal_amount       = safe_float(payload.get("savings_goal"), 0)
    target_months     = int(safe_float(payload.get("goal_months"), 6)) or 6

    # ── STEP 2: Goal-driven maths ──────────────────────────────────────────────
    monthly_needed   = round(goal_amount / target_months, 2) if goal_amount and target_months else 0
    monthly_saveable = remaining
    total_saveable   = round(monthly_saveable * target_months, 2)
    is_achievable    = total_saveable >= goal_amount if goal_amount > 0 else True
    actual_months    = math.ceil(goal_amount / monthly_saveable) if monthly_saveable > 0 and goal_amount > 0 else None

    # ── STEP 3: Budget allocation ──────────────────────────────────────────────
    needs_pct       = round(total_commitments / take_home, 4) if take_home else 0
    raw_savings_pct = monthly_needed / take_home if take_home else 0.20
    savings_pct     = max(0.20, min(raw_savings_pct, 0.60))
    wants_pct       = max(round(1 - needs_pct - savings_pct, 4), 0.05)
    if wants_pct == 0.05:
        savings_pct = round(1 - needs_pct - 0.05, 4)

    needs_amount   = total_commitments
    savings_amount = min(round(take_home * savings_pct, 2), remaining)
    savings_pct    = round(savings_amount / take_home, 4) if take_home else savings_pct
    wants_amount   = round(take_home - needs_amount - savings_amount, 2)
    wants_pct      = round(wants_amount / take_home, 4) if take_home else wants_pct
    wants_remaining = round(wants_amount - total_spending, 2)

    # ── STEP 4: Savings projection ─────────────────────────────────────────────
    savings_projection = [
        {
            "month": f"M{i}",
            "projected_savings": round(monthly_saveable * i, 2),
            "needed_savings":    round(monthly_needed * i, 2),
            "goal_amount":       goal_amount,
        }
        for i in range(1, target_months + 1)
    ]

    # ── STEP 5: Goal status text ───────────────────────────────────────────────
    if goal_amount <= 0:
        goal_status = "Enter a savings goal to see your projection."
    elif monthly_saveable <= 0:
        goal_status = "Your cash flow is negative. Reduce expenses before targeting a savings goal."
    elif not is_achievable:
        shortfall       = round(goal_amount - total_saveable, 2)
        suggested_goal  = round(monthly_saveable * target_months, -2)
        goal_status = (
            f"Your goal of RM {goal_amount:,.0f} is not achievable in {target_months} months. "
            f"Saving all your remaining cash (RM {monthly_saveable:,.2f}/month), "
            f"you can only reach RM {total_saveable:,.0f} — short by RM {shortfall:,.0f}. "
            f"Realistic options: extend to {actual_months} months, or adjust your goal to RM {suggested_goal:,.0f}."
        )
    elif actual_months and actual_months <= target_months:
        months_ahead = target_months - actual_months
        goal_status = (
            f"You are on track to reach RM {goal_amount:,.0f} in {actual_months} months"
            f"{f' — {months_ahead} months ahead of your {target_months}-month target.' if months_ahead > 0 else '.'}"
        )
    else:
        shortfall_pm = round(monthly_needed - monthly_saveable, 2)
        goal_status = (
            f"At your current pace you will reach RM {goal_amount:,.0f} in {actual_months} months, "
            f"but your target is {target_months} months. "
            f"Save an extra RM {shortfall_pm:,.2f}/month to hit your target on time."
        )

    # ── STEP 6: Prepare context strings for Gemini ────────────────────────────
    spending_lines = "\n".join(
        f"  - {item['label']}: RM {item['amount']}"
        for item in snapshot.get("variable_spendings", [])
    ) or "  - (no itemised spending provided)"

    commitment_lines = "\n".join(
        f"  - {item['label']}: RM {item['amount']}"
        for item in snapshot.get("fixed_commitments", [])
    ) or "  - (no itemised commitments provided)"

    benchmark_25_34 = get_age_benchmark("25_34")
    utilities_benchmark = benchmark_25_34.get("housing_utilities", 1201.69)

    anomaly_lines = "\n".join(
        f"  - {a['category']}: RM {a['your_amount']} vs DOSM 25-34 benchmark RM {a['benchmark']} ({a['flag']})"
        for a in snapshot.get("anomalies", [])
    ) or "  - none detected"

    bill_context_lines = snapshot.get("bill_context_lines", "  - none declared")

    median_income = safe_float(benchmark.get("avg_income_median"), 0.0)
    salary_gap    = round(max(median_income - snapshot["gross_salary"], 0), 2)

    # ── STEP 7: SINGLE unified Gemini call — all 6 AI features ───────────────
    prompt = f"""You are a Malaysian financial advisor specialising in fresh graduates.
Analyse the following profile and return ONLY a valid JSON object — no markdown, no backticks.

=== USER PROFILE ===
Name: {snapshot.get('name')}
State: {snapshot.get('state')}
Gross salary: RM {snapshot.get('gross_salary')}
Take-home pay: RM {take_home}
State median income: RM {median_income}
Salary gap vs median: RM {salary_gap} below median

Fixed commitments:
{commitment_lines}

Variable spending:
{spending_lines}

Remaining cash/month: RM {remaining}
Savings goal: RM {goal_amount} in {target_months} months
Monthly needed to hit goal: RM {monthly_needed}
Currently saveable/month: RM {monthly_saveable}

DOSM 25-34 age group spending anomalies detected:
{anomaly_lines}

Key DOSM 25-34 benchmarks for reference (RM/month):
  - Housing, Water, Electricity & Gas: RM {utilities_benchmark}
  - Food & Beverages: RM {benchmark_25_34.get("food_beverages", 826.54)}
  - Transport: RM {benchmark_25_34.get("transport", 538.25)}
  - Restaurants / eating out: RM {benchmark_25_34.get("restaurants_accommodation", 941.25)}
  - Information & Communication: RM {benchmark_25_34.get("communication", 327.18)}

Phone/WiFi/bill items declared by user:
{bill_context_lines}

=== YOUR TASKS ===

1. SPENDING TYPE: Classify this user as exactly one of:
   "Lifestyle Spender" (high food/entertainment relative to income),
   "Committed Spender" (most money locked in loans/rent),
   "Stressed Saver" (trying to save but barely making it),
   "Balanced" (healthy split across all categories),
   "Under-earner" (salary too low for cost of living in their state).

2. SUMMARY: Write 2-3 sentences directly to the user about their financial health.
   Be honest but encouraging. Mention their spending type and one specific number.

3. HEALTH SCORE: Score out of 100 based on:
   - Commitment ratio vs take-home (lower is better)
   - Remaining cash after all expenses (higher is better)
   - Gap to savings goal (smaller gap is better)
   Use "Strong" (75+), "Needs Attention" (50-74), "At Risk" (<50), or "Tight Budget" for borderline cases.

4. RECOMMENDATIONS: Exactly 3 ranked recommendations. Each must be:
   - Specific to Malaysia (mention real services: My50 pass, PTPTN repayment moratorium, ASB, PeKa B40, etc.)
   - Tied to a specific RM amount this user can save
   - Categorised as Easy / Medium / Hard

5. GOAL SCENARIOS: Generate exactly 3 "what-if" paths to help the user reach RM {goal_amount}.
   Each scenario must have a concrete action, estimated monthly saving in RM, and new months-to-goal.
   Calculate new_months as: ceil({goal_amount} / (current_monthly_saveable + scenario_monthly_saving)).
   Use realistic savings amounts that are achievable within Malaysia context.

6. INVESTMENT ADVICE: One short paragraph (2-3 sentences) advising whether to prioritise
   EPF voluntary top-up vs ASB vs both, given their income bracket and remaining cash.
   Be specific about Malaysian products: ASB dividend ~4-6%, EPF ~5-6%, ASNB funds etc.

7. BILL SAVINGS: Audit only phone bills, WiFi/broadband bills, insurance, and subscriptions.
   For PHONE BILLS: compare against Malaysian prepaid/postpaid plans — Maxis, Digi, U Mobile,
   Celcom, Hotlink (RM 35-50), TuneTalk (RM 20-35). Consider the user's likely data needs
   as a fresh grad (Grab, social media, remote work, streaming).
   For WIFI/BROADBAND BILLS: compare against Malaysian home fibre plans —
   Unifi from RM 79/mo (30Mbps), TIME from RM 79/mo (100Mbps, selected buildings),
   Maxis Fibre from RM 79/mo (30Mbps), Yes 5G Home from RM 59/mo (25Mbps),
   U Mobile Home from RM 55/mo (25Mbps). Suggest the cheapest viable option for their state.
   For INSURANCE: flag if the monthly amount is significantly above the DOSM 25-34 benchmark
   of RM 216/month and suggest reviewing the policy.
   Suggest a specific plan name with its RM price and actual monthly/annual savings.
   If the user is already on the cheapest viable option, return an empty array.
   If no auditable bill items were declared, return an empty array.

=== RETURN THIS EXACT JSON SCHEMA ===
{{
  "spending_type": "Lifestyle Spender",
  "summary": "Direct 2-3 sentence message to the user...",
  "financial_health_score": 62,
  "health_label": "Needs Attention",
  "benchmark_comparison": "Slightly below regional average",
  "ranked_recommendations": [
    {{
      "rank": 1,
      "action": "Switch to the My50 unlimited public transport pass",
      "difficulty": "Easy",
      "monthly_impact": 150,
      "reasoning": "The My50 Klang Valley pass costs RM 50/month for unlimited rail and bus travel, saving RM 150 vs your current transport spend."
    }}
  ],
  "goal_scenarios": [
    {{
      "label": "Reduce dining out by 3x/week",
      "action": "Cook mid-week meals at home instead of eating out",
      "monthly_saving": 150,
      "new_months": 14,
      "difficulty": "Medium"
    }},
    {{
      "label": "Find a housemate",
      "action": "Split rent with a housemate to halve housing cost",
      "monthly_saving": 300,
      "new_months": 9,
      "difficulty": "Hard"
    }},
    {{
      "label": "Side income via freelance",
      "action": "Take on 1-2 freelance gigs/month on Fastwork or Upwork",
      "monthly_saving": 400,
      "new_months": 7,
      "difficulty": "Medium"
    }}
  ],
  "investment_advice": "Given your remaining cash of RM {remaining}, prioritise ASB first...",
  "bill_savings": [
    {{
      "item": "Phone Bill",
      "current_amount": 80,
      "cheaper_option": "U Mobile RM 35 plan (15GB)",
      "cheaper_amount": 35,
      "monthly_saving": 45,
      "annual_saving": 540
    }}
  ]
}}"""

    try:
        ai_response  = generate_text(prompt, max_tokens=1800, temperature=0.2)
        cleaned_json = ai_response.strip().replace("```json", "").replace("```", "").strip()
        plan_data    = json.loads(cleaned_json)

        # Validate required keys — fall back per-field if Gemini omits them
        plan_data.setdefault("spending_type", "Balanced")
        plan_data.setdefault("summary", "Your financial plan has been analysed.")
        plan_data.setdefault("goal_scenarios", [])
        plan_data.setdefault("investment_advice", "Consider opening an ASB account and setting up a monthly auto-transfer once your cash flow stabilises.")
        plan_data.setdefault("bill_savings", [])

    except Exception as e:
        print(f"Gemini call failed: {e}")
        # ── STEP 8: Consistent fallback — Python score fills in ───────────────
        py_score, py_label = health_score_python(snapshot, benchmark)
        plan_data = {
            "spending_type":       "Balanced",
            "summary":             f"Based on your take-home of RM {take_home:,.0f}, your fixed commitments are RM {total_commitments:,.0f} and variable spending is RM {total_spending:,.0f}.",
            "financial_health_score": py_score,
            "health_label":        py_label,
            "benchmark_comparison":"Calculated from your profile",
            "ranked_recommendations": [
                {"rank": 1, "action": "Automate a savings transfer on payday", "difficulty": "Easy",
                 "monthly_impact": round(monthly_needed * 0.1, 2),
                 "reasoning": "Paying yourself first ensures savings happen before discretionary spending."}
            ],
            "goal_scenarios":   [],
            "investment_advice":"Consider opening an ASB account once your cash flow is positive. EPF voluntary top-up is also worth exploring if you have surplus.",
            "bill_savings":     [],
        }

    # ── STEP 9: Inject all Python-calculated fields (these are never from Gemini) ──
    plan_data["budget_allocation"] = {
        "needs":   {"percentage": int(round(needs_pct * 100)),   "amount": needs_amount},
        "wants":   {"percentage": int(round(wants_pct * 100)),   "amount": wants_amount,
                    "actual_spent": total_spending, "remaining_buffer": wants_remaining},
        "savings": {"percentage": int(round(savings_pct * 100)), "amount": savings_amount,
                    "monthly_needed": monthly_needed},
    }
    plan_data["target_months"]         = target_months
    plan_data["savings_projection"]    = savings_projection
    plan_data["goal_status"]           = goal_status
    plan_data["goal_amount"]           = goal_amount
    plan_data["monthly_needed"]        = monthly_needed
    plan_data["monthly_saveable"]      = monthly_saveable
    plan_data["actual_months_to_goal"] = actual_months
    plan_data["is_achievable"]         = is_achievable
    plan_data["anomalies"]             = snapshot.get("anomalies", [])

    return plan_data


def analyze_profile(payload: dict[str, Any]) -> dict[str, Any]:
    snapshot, benchmark = build_snapshot(payload)
    snapshot["savings_goal"] = safe_float(payload.get("savings_goal"), 0)
    snapshot["goal_months"]  = int(safe_float(payload.get("goal_months"), 6)) or 6

    # ── Single Gemini call — no second call for summary ───────────────────────
    plan = build_plan(snapshot, benchmark, payload)

    # Bring summary up to snapshot so FinancialSnapshot.jsx can read it
    snapshot["summary"] = plan.get("summary", "")
    snapshot["spending_type"] = plan.get("spending_type", "")

    finance_gaps = build_finance_gaps({**snapshot, **payload}, benchmark, plan)
    plan["goal_amount"] = safe_float(payload.get("savings_goal"), 5000)

    pipeline_state = (
        "high-risk"     if any(g["severity"] == "high"   for g in finance_gaps) else
        "moderate-risk" if any(g["severity"] == "medium" for g in finance_gaps) else
        "stable"
    )

    return {
        "pipeline_stage": "finance_gap_detection",
        "pipeline_state": pipeline_state,
        "snapshot":       snapshot,
        "finance_gaps":   finance_gaps,
        "plan":           plan,
    }


class FinancialAnalysisHandler(BaseHTTPRequestHandler):
    def _send_json(self, status_code: int, payload: dict[str, Any]) -> None:
        encoded = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        self.send_response(status_code)
        self.send_header("Content-Type",   "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(encoded)))
        self.send_header("Access-Control-Allow-Origin",  "*")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.end_headers()
        self.wfile.write(encoded)

    def do_OPTIONS(self) -> None:
        self.send_response(204)
        self.send_header("Access-Control-Allow-Origin",  "*")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.end_headers()

    def do_GET(self) -> None:
        if self.path in {"/", "/api/health"}:
            self._send_json(200, {"status": "ok", "service": "kyouth finance backend"})
            return
        self._send_json(404, {"error": "Not found"})

    def do_POST(self) -> None:
        if self.path != "/api/analyze":
            self._send_json(404, {"error": "Not found"})
            return

        content_length = int(self.headers.get("Content-Length", "0"))
        raw_body       = self.rfile.read(content_length).decode("utf-8") if content_length else "{}"

        try:
            payload = json.loads(raw_body)
        except json.JSONDecodeError:
            self._send_json(400, {"error": "Invalid JSON payload"})
            return

        # Input validation before touching Gemini
        gross_salary = safe_float(payload.get("gross_salary"))
        if gross_salary <= 0:
            self._send_json(400, {"error": "gross_salary must be a positive number"})
            return
        if not payload.get("state"):
            self._send_json(400, {"error": "state is required"})
            return
        if safe_float(payload.get("savings_goal")) < 0:
            self._send_json(400, {"error": "savings_goal cannot be negative"})
            return

        try:
            result = analyze_profile(payload)
        except FileNotFoundError as exc:
            self._send_json(500, {"error": str(exc)})
            return
        except Exception as exc:
            self._send_json(500, {"error": f"Failed to analyze profile: {exc}"})
            return

        self._send_json(200, result)


def main() -> int:
    server = ThreadingHTTPServer(("0.0.0.0", DEFAULT_PORT), FinancialAnalysisHandler)
    print(f"Kyouth backend listening on http://localhost:{DEFAULT_PORT}")
    print(f"Dataset: {SUMMARY_PATH}")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nShutting down...")
    finally:
        server.server_close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())